# Generated by Django 6.0.5 on 2026-05-11 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=20, unique=True)),
                ('room_type', models.CharField(max_length=50)),
                ('total_beds', models.IntegerField()),
                ('available_beds', models.IntegerField()),
                ('floor_number', models.IntegerField()),
            ],
        ),
    ]
